apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvidia-gpu-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nvidia-gpu-demo
  template:
    metadata:
      labels:
        app: nvidia-gpu-demo
    spec:
      containers:
        - name: gpu-worker
          image: nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda12.5.0
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
              nvidia.com/gpu: "1"
            limits:
              nvidia.com/gpu: "1"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nvidia-gpu-demo-svc
  namespace: default
spec:
  selector:
    app: nvidia-gpu-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
