//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *RuntimePackage) DeepCopyInto(out *RuntimePackage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *RuntimePackage) DeepCopy() *RuntimePackage {
	if in == nil {
		return nil
	}
	out := new(RuntimePackage)
	in.DeepCopyInto(out)
	return out
}

func (in *RuntimePackage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RuntimePackageList) DeepCopyInto(out *RuntimePackageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RuntimePackage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *RuntimePackageList) DeepCopy() *RuntimePackageList {
	if in == nil {
		return nil
	}
	out := new(RuntimePackageList)
	in.DeepCopyInto(out)
	return out
}

func (in *RuntimePackageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RuntimePackageSpec) DeepCopyInto(out *RuntimePackageSpec) {
	*out = *in
	if in.TargetArchitectures != nil {
		in, out := &in.TargetArchitectures, &out.TargetArchitectures
		*out = make([]GPUArchitecture, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *RuntimePackageSpec) DeepCopy() *RuntimePackageSpec {
	if in == nil {
		return nil
	}
	out := new(RuntimePackageSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RuntimePackageStatus) DeepCopyInto(out *RuntimePackageStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
}

func (in *RuntimePackageStatus) DeepCopy() *RuntimePackageStatus {
	if in == nil {
		return nil
	}
	out := new(RuntimePackageStatus)
	in.DeepCopyInto(out)
	return out
}
